# SealedSecret — imagePullSecret for the private Harbor image
# harbor.capstone.uamishub.com/slidedeck/slidedeck. Sealed (strict, ns+name
# bound) for secret `slidedeck-pull` in ns `slides`, which deploy/deployment.yaml
# (app repo) references under imagePullSecrets. Backed by a pull-ONLY Harbor robot
# scoped to the slidedeck project (robot$slidedeck+slidedeck-pull).
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slidedeck-pull
  namespace: slides
spec:
  encryptedData:
    .dockerconfigjson: AgAthFqK7lX8ltMpSCWAANKbaf2qUVJ9frFrmjO4AORkKjeMKeGb/TmxUxBvDB+KtvlycYiTtyg3DLZR6xAu7QZGwpwnQrSvr+wERqC91F5nfyJovpLKfqcLW+5z8YCy6DYiNBti4zhR0ArFFfVmHMx2Rm7yydWAD0czJv45s8ofskzHO0UQLK6Wz32sdrGUKbhbl+GgWKL+i6ZGkiOjd9J1Q3XivDvBiU6cNOmAgrIAGSNxcOYjEjHuBOG61BAXDxKXhwSIflsOwJ1HsMG8Cp2Y++QZzaMA1Iqbs/DIXC5Q/rtChH3m8/euQEkGTviqBRHLJykYz2H9uNNzBV9pLX/HUdJ28pkzpkq8HThQW403ebck/i4lq2eCmNJfLRBZ8jeh4pzCDcbzNsGFZYr6UEkisg+HXocCi1ruVWGlSov0wljQl3MKR2kplnLe4m1rl5c25LENtuyTVZqE4RUDmohSceg1T9/eEbuF6NV86iCRenHlrfS8Gu+KdNBswkgDczbaljITAfanlAAzu535YeTeqKtLW607EV7nWNJnqnt+j241YAscIcZymFpgkN7zkLFphGd7VpVjr6O5ZAhwucgZIAgkLboaAhnvbk2pHKn+vEvGR7WY6a1SmlnCKonC2m3tzXt00V8EThxZJM9sK1nikOep7qGOup3GNOJibtVSMXqQfmriWOEnvREE03H2Sl3/3XOzE5T1TBtgmCEoz/syFCmee00dCsvI0RC8ip+zf5aYLs14X3OOrtEfD9ZLukc0fo8QnlcAw67fpzS7L875kholyk59/7RoFpq9L4Dur9WjIzTmilSCQ8Sj/gSXY+gvAigKGNHfbxs0+SATsMuXI4iCmjEqCpgCGUxXs/y1Kh1K0wsXqZE44cugNTokOY3Jo2KSSnpSrdPeF12AeH38iKRDRGATMdYY7Sd6BdnDbAb4eDplxMLcKolQi521sNo/uYvI38vYU+WR1ABWnTowk5rO7hfrXw31hDjyFRs5rG0fwfk=
  template:
    metadata:
      name: slidedeck-pull
      namespace: slides
    type: kubernetes.io/dockerconfigjson
