---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-postgresql
  namespace: backstage
spec:
  encryptedData:
    password: AgCu2gD1vUwLBYVSl4foYDajMgI3u9Ui0OoeVq/uuetT1op+9p6bDM8Z8W9mxaMPpAMBPCa+JqqNDHXlr+t9fKbmUSaYzuq0JXZdTax07azOMd2stvYeR+8k95Ps8Jybw7F0g4T736AO2q49ICiNHHgAuo69jexI/x4j08XTL8OAG9PGImFOsh9kEMrxGb40d70mPvDbwUQe4ndTSiwzWrYfBWmKE3hSznmebDqEQyH8fRXrA0K75zc4KahSRJdKfpaDHymogFdkbqDbN+48Q2jyPIOHyZZRryIIbjnfxaWUtlPqydc1r8tl62OQteiUpid5oFb/ozpAE14mb25s/q+onNHneRDqnWicYBPwKpDve45Y+dpxp+1uxVcPLyGcMQPcZFEHAn3VDZaHl1k3EN7CUzuNPRCfEQ8GKAbQudgfPihnDMMXZhzinX5r44MSdf6wTl4KM5jy4RzH7XyYCkkN/k5N3mfi8F+vX1Ss+v7P9RrPxKPjPJphBN3tn6vmiw2/Gl5UjYy1UA2lVY9SD5vSb4jmPR/S45xcQghkN7tJ0NeoAcjrZc71I4Ka4rMGleaLYo81PANk4tylAuZ2++ixP/C/vyzdLeYVBr8bw60YdskRQFddTnXYNmFrR/GyyOMV0XbtRiQ8ba1y1kCeBq7tSA0nE9IZgv+6BIbWyvqVdeewC+erqz429miKQPJ6oTKHmIZeblUsxmgZuJkXD0a5K9om+IJV2lm57A5QAgifjw==
    postgres-password: AgCF2ndyiZLA8+PA6UcaklItoXVR6Je2l3LFYVCK7LU0SIpk98tm6qLjX88RBlalKRvwIwqpiGoHyL5mLiEOochjtaUzbg2phVS50MdWuXfenrSZjyWP1BDgQNjdY2P89E7hsLxEFmp2d1vE8RH854BpXkktfJuVvItx3OfmTURb2bKFfrBXNai2Zk2SacawcYsXJAUA/7KOmvdELqwFRaGCGlWCM4TRyP1iqXHWRRsAWUn47OQKr0YgvYS//EmW55FlLp5tcILUA/zXr9FOPWDETAh7lbmZhNvHGeGdrwLzxipQ6k0P/5c+eoS9UeTVomsRbOIEeZ35klWgKm7vJLYFuFAMVBz/cohPxEvG2hf+xQeP7AQOVQ4/XrXBM4cV+IW7TCeZvTvcXUSC3kEa4flx52AyOwSzsUyzNrz+iVwZXZdS4OaeaNd//egTqDrnDy4qAA08RbV1pPb3huvbrpKJcaTbsHLHH4BbkJ7wEJZzLzzJgpB9uudtg/qXrsihQH6vLAft9/GtA3kXJ4Ta1Z84jcAOSUY0N/QfzaRS/Mx9yStoZki7wCd+dHdtjmpW/4UabKkmdT6EOQhjq14CddAx73nqFEIBjMb3OzXHCVpK2JrmGaoVca/iqUnfLGPyh0Q7XIS3443S8C/6JHq7UV5vu4+SoYbwJppjRHEA/aG5v7rxZTM4EQTMRKOpN8+e3iXLuV6wj9Y1k4stvgwm101M/LtjPmjGfpe8SdnrtGSYhw==
  template:
    metadata:
      name: backstage-postgresql
      namespace: backstage
