---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-webhook-github
  namespace: argocd
spec:
  encryptedData:
    webhook.github.secret: AgAMbIhpkfBC1rfSptdJLyJYHH9SClw6myj2ksRnYQTjrKz+/YOZKDXPMSok7hBFTAtIiGxWH1bo/KHm6lOvfO1opeBW/EBVjgJrK8JSmEo6uDpP66itZU0Df9Lu+oob+GWHi2oqdzZUoOsm1WwSv9EIjhirHdciNBdnLTvvT/rpItyMuIrzcvaPdAtR0EkdscYn4opyrPkk0eTMBAI/zXI7fa2xwYeiZZKE5yDBuctC4XNcBaglDxUZc43VBRkBOzhJSot2u/nPsQM8zrC5of4J0Bp9u3XE4EtfWWHIOHCK5mB3wicYgZUx+98w90S4j09F1m4r0T26XIXqiKQl4HSotfgkG94BSiYhX2DLn9IVMUJK1nhaQ/+Exbjf0beThJ/YyN/PFzsDT2arTMb0jGdU01zOV8G710p50t3XBFvKYmWsj9oanHb104tMlob6dOM4a1cRl7eHpTlftWrAnQQNUK7x6eOZhLlK+T3Lw+5WxqQd9rusegZD3D8Wcv2ZOS2biuK0ypUdFkgNjTiJ9RKAwF4/ejVxe0AYN0pMdYojU39PdG0Sbm6/mfMHJmsj+G3+XUhRVmoVh/lQr+7DUw4VlNMhJO6r16Z8cFhvtDYgoDAHr5DDGp1WlPgD6NMUSjA58KYXQC+AV/lvUqteDClNhJzjOMMTU/RBcHKO9LeMillkIHeTH2usMAhpD1rEzQ2Z3FNjpOmve9W2YBsYRzzT5mjkXdIZ2DKN1fGd97ixxIm136hVvU7cG7tHe+gZRG0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/patch: "true"
      labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
        platform.capstone/component: platform
      name: argocd-secret
      namespace: argocd
    type: Opaque
