---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-pull
  namespace: ida-slides
spec:
  encryptedData:
    .dockerconfigjson: AgAkOhyC+mCpraNIMwCDWgwYc1eZc86C9hGA5/IhZbEieukUQwlHHO9CdThoxuxr0dMsmEvvxd7zruJkTcNFjKInllYzWCMYrTKaN3xeGEaSyID/QKfX+La1RlJwnT0bx0mEwrjUlRb9ov+po+CTav4ztGiefxUrMQ+WFIPDMZ69wQEWncccV3sg2fHo7izx/vQitVgZPS5xMY7eFBUuzRgFdeT/Q7L/anJRUWhilJNh9Do+54W1/61b+lkGXWn2skmS91OiTSaQWwFbZ0JBSoj75RTZqZkKBdaCitdpWnKeMTQr3xUUgVONKQ8v4/RG5VQ6xHnsP3A+K4h5BYTMIdSNR8Fr4k+e8AMzhOA3xW7Z0fcDa+KuaeGXqGsR+c3wUKH63GAx1c63kEfGbrI4a0LLxMmlmOKDi+JmGYdRSZ+QerdHKcxEdwxYTwNU05FBAuG4VjS+lcngl/BrW8X74FrndCLPxNaORc5VPHmFMyD24dJoH4PE6piB4DOld0pZQwT2TaqVPzCdEh0rCXjpiP31G5/94GgGI8r4BRpF8DOQF+gAxmedUz1IjEz7vXUb8GWO8FPW6uHQery7PWVf/RZ/nay1F9WdhdxSPGWmbqy6tY9BWF21Y7IEJH6cXe1jsHHde+B7LRRBG5l+6U3T6l9r1BBseIVBInDg4FyF+iVY8flNv40DkBiBdbG+roAoISgaZu1um3FddhoM3g13+t8QTQR9wqtcF2dXtBSAvpdohhKeiIAp15HkFtdohu+I9gtGS5fquIK9bYpWL/hT8OSEnmeiIilrKrjdwm5FEChkWMoPBNqkNBScP4QnMH+cdEPLn3eK8pfQeeElwhBrcfjNwkLMus2agR7PZvgnSYTKDjJHCC2fRQjiZYydDKV88tv3sCmX4hZqSXRuqVNqvwumWpPO4siB39Cz8WxuCM9DYwE6y47OA/7T5faG4g8BzJq+fgLbgRzSfDqkaMIf6fuLfGgvEDwl4MdtJesrl7pTIqQh0nXp1/odC/M=
  template:
    metadata:
      name: harbor-pull
      namespace: ida-slides
    type: kubernetes.io/dockerconfigjson
