apiVersion: v1
kind: Service
metadata:
  name: portal
  namespace: portal
  labels:
    platform.capstone/component: platform
    app.kubernetes.io/name: portal
spec:
  selector:
    app.kubernetes.io/name: portal
  ports:
    - port: 80
      targetPort: 8080
