---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-thanos-user
  namespace: minio
spec:
  encryptedData:
    password: AgBWxSIL4e0NFFecE4o3ZpPQUsU4J8SV8H17O6MEGPIf76nVJZbZQGntoHUuqvh0Z6uwOCzq6cLzGfJgfLq+L4j2xfodTnUR9E7oz/Zqky93BDer1Mfn9SgiEZYYo3cjLSakMoLniu2RfDCpxUWMWkmjJyN0qB3cUxtX/GT+Rdu1T5+aXF6BEaNyKhukkiNx5CJ99U7RfRFjA1+NVIZzsmXfBlpaKds22lIhebk7WTVchWLYEsxWD+iTxziAoyS2DU9111bj+w/oMMW2ocDpLaC9t6l7p2gPw9cpyczAv7Nj9Bv8S6vd7/4XzqCFrJmJCBE8OoEMMWnPyC0nzTgMrPmjbHxKpfu0T/JXAVhzucGLScSX4p6TS5ifVYfGoDLoBdChmoBMaIJQB9lJv1ay/c9n7N6j/MDfTRrSWfNQmnYDXTsYASaZKDq7GtOE2USJYmJEP0R9osBcOJOM9UlFicktPUL7ooslZBAhX3CJk2IQcX0jOdeyFLrQim30Pbl1IAr5w9yyLsMttv7+3EISFPP3bFkkowwX8QYxBrCobaCbLWpWZInDUlUs+lZSQfbmyOZlKUQGx7P7X1l41nn+R/1wEzmNGozUbI5yaFNvnE5J4e4kBlqUBVVpdbDHG19Yi/p2TYDKLZZv4+uVg7/IZdNI7t6zj86/RIySyjBA841PITLumoW3hQtyBio5jmtJAEwlHPu9mb1jGWwT/QytpsJYuEx8z6msgas=
  template:
    metadata:
      name: minio-thanos-user
      namespace: minio
