---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-webhook
  namespace: monitoring
spec:
  encryptedData:
    url: AgAPxrfY+hUzNQivZWdkp0fP7ElsDferTKRk1vs1UQ5ug/gOuTBRkUPvJ3AaocYLnlGUh69kTOVImXMu4BTxsidGDL4eVk8EsLWHmTDvwo5SN7VaWMBwdPVF6fJbD5bWt0xs+TD0j9XFLN7snixFI2Q1k+P8MLFn175X/FVKTgfAoNu22pmYK3ICCHYmkanKunc7xL1L7Oh/T7sU7wQl2MVd4Yj7wu4LFj14dEi8lRlleBfX1VPKLMyBdrsAeuLpChyr5HVAE2JOoj1Djh/mIwCssjRmJ1SoWSgGdvcKKyOh+LxcxDVYAlMaVWrnYUFrQLB61DuRXVBB1VU2RGTJuLxTt2cMbuAZSK1K4YmIIOmLnjs/IhXFMIT+eD5FvDigIr3w/wyIKe7Jh2FWe6y6IRAcXtDQYF1ALIJpY208PtcN8yAvyvqXfIgA8wfUYpCer12ahFLNbPpiXVZQn2sG5+noZ/NnzvUke9SVgzWzJe7G0uauDP9EvQ8sYWi06ky7MkxDIBhJfjL7GtWesllTuULkSRVOP2DUVkwVVeG9bs7xhKrHFgkdDqtHzJ7rnhnhTFD+K5SU3nFh47+gfhiCdOtJ5DTKsVGTRS6bJndxNZVuPhH0yS0oOy0CDUZS4Kfzk9wVvu8h+pH28WnRCz6+O3g9p1zDXiuT2Z/ujdDrvQGEwtSmeE63QsB7usTSZ1NudKS5ImfLUe8kZjFMnNpMcYLD/kT8RmZCu5FWdejICkJYluMo8jvDC1GgkjJQ+w==
  template:
    metadata:
      name: alertmanager-webhook
      namespace: monitoring
