---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCjyhzLio7qyCGMNWE6vpWz9ABqM/x1w3Psust3aD9rAsQN3TVypEQlQSxlsYlsnVvsxuWzFEWPfWRaZSwheTzj3XbTZEi5gjllbXd9Qbthe4cRRQ0cRn2ftumwsdDZ9CrEKBTh2A7ivZxLqq57MQbSKDvvrH6eigOFD96YyjngPLOIdSV7OVCkG3QVMCOP4IG1cIMqlYCTm1p2U2qaJe9Gp9h0WNzVFgxnyO9/E1qsfY2rqEpF+tnfEOu6N0IX6nELz2a+CUF0BrWK1PDtili+dYMjm+ndueohnxpJ+2BFdnG2qjmSnGkbeAzj0CXKk+NU2lcqoeRwQeNOyGbuVBX+o1Q0go7stUkxybYAhZ8+AkuGmX2ukftgPp3rJBSvo34mHZV+ItztiWEtSO/jtDRzOUl/7NgEtKnbrl+bbkxrgvDZfzYtXM1guxVYpZ7Jjamsi7WwAs1gEBqp+xpGpzBkXUh93+rkKA3NduYu0FK2T/Oo/Z5M43yT97rtQ/LNucr+0x2ptQL1C6VNsk5kCe8YnKnclM0BD8/Fea/Rw/1/sgL6RQVfsH0A19b+wT9DYiDd1ZvIzoF3tfX8ZSJ1xIE9+BYaZY75IurhzKn+f5mTcHZ9OU2wOPB3+qcTkUsBlG17uuk1Mzt1NH1bGPte3W0Pk3UD8FeTqDiJag48DCICQFKSVM/CJof5bjG4tNe+ezx/N+TN9tkf8bNTzTGn/wDwZU79tfW3Yuw=
    admin-user: AgApthJsxGZMGMAuwIi1PFaSiYzvAiYaN6FdvqEr8dJP5YHxmcIbajbBGZzkB9xF4YIzCtPSpOyI3UU1A8TEr/QW4DAnj7L9ONrOKPgk/XIGWF1sfUT1fR7+EeK2vNskjZUT1boilUrVfMMuoAEc4R+LcFsbzWlvp64qXWn/3tKVWPTwkNtvycR0kDk6g7nTaSBrvqrqKBi9Ma2Mv9c6qBFCfGhb3PF4BNyO4XoIrRoypeyaxcAfC7hwq70RHlyUw/B9aYB1nSwRYYcDLF/mRyYUMI62/qN6sFw3lAbYleOdvEQQrn9cRKaCnN9LHQiD5XZcQfLxtbRI86ze0y6o1ggWpQBhVUla0u80KhqEjPZgHVHYs/8/LON1dF4kXAxY9FyUJCDSG0E+/2y7QVnPTyWaIb1vEgEl0HGFxsUgw9ghSZ1BnJdofOL5WKTX43S4njkgINYpprKcTNkBlBAXf+8YSpzQhdB4SJHHOHZxnDkeG5i7roRGrJAGV0J6SLx6d4wEfkNQE8hqBXCaVYdESevysApOdSwC3Ugtnvo2kW0FUTasjfMake89ele1F85hqXE8eUDcVdO8zwcex1e6hzfxrT5/jv64uBJs30xePbgZZoktjq0922A8oR/If+msAvWWjLps2KJwwAMMx8mD3SNdvrNwQ8yBaKvopN7AE9FpKqM+YtWsoFqCsLZUZvjqTRDzm5IY6Q==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
