---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-webhook
  namespace: monitoring
spec:
  encryptedData:
    url: AgAqvdE8NTd/mE78L72wvTHxc61IaJl1xUNSDDO8HQommhRaPieLP/uEh7wIhtvnMwDHUHRw2YWnpYtM3yJXyRyJRtZKqrHoa8oCnvEIsLMn7bc6nRDeDnKcJ6/E4j2FHgIdC/rm1WG++5FNXaQHm3ISTVWZGZHNonWtFZTBvUzaXDmYqOiLtdzz+el/YfrWYM+qg7T9AAUYEPQHxW6n0pzxleQRX9v42RKvjUjXi85MHdDlJzpQCkGbcoAS1M3BpsKwSwJppAIOKS5Hhg2SD8EkYrSdpYRaaRJX3yIMulW/w/o8k3Ip+cEWa4vBPPVsjUF8VhX/XDCkuXydySjwkzty5lb1lClMWY6UObBwHZju+3ImVl+a5yteSxN/siL/+SV2oDSUVEZ759tNihcmu/aJHnznj27ywWZ/HqAeWqLULbJ6WtKYod3/s2pjsEuocn7YLVXUujcshy7P3EV/pWnAWDG0RLvhBMwHI5t8aJVZOmlMWXgb6IiE/LTwJ966NNI6euq6945xhPTJojZlatKVjiLOT+5w3qgZO+RoE/VkoW8Qju60ZD6HysRtR6LRHhBx5BtttqQFLraO57WuSDsqOhys9yWIKSuZ/MrmcNU7qjiVFKJMuisLQtSwSQQFrJo1kKE4vLTGcArzoK6coR2649pOX3/vEXGYrOz2ZmfKoNmYDujxbaQjYEDUi99+evhA+NnuoURuXEDB5d6l1ZN5d93Gf21dOUEdoH8ZuT60D+IaDl8KEn/76M33lZ5OlC1Q/Y6g3Ap46Qa/ob2f4tlfEIzxDBgj3mZrztWx/lTwh8ozRang+03DZXYMzGCPu56+phiUI9uF/BJVFFAuB9NkFdL7kaZ6z6ampXfx
  template:
    metadata:
      name: alertmanager-webhook
      namespace: monitoring
