---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-pull
  namespace: agile
spec:
  encryptedData:
    .dockerconfigjson: AgAgIfhsmVflsiRp/YQechiHlXf/MV5NbHWjEjGGdMv4SUtmIy+s7qAII4JxhIOgHBNAh3k03CJrDSD5CX65QQZ9tBUNnppK5bwtK5EdeWs5dIdRYzUCdGFZaFEBndWlUU9TtUHDo6H46bAqrz0DpdKBlh8xRr70UyG91k+tsJAD5/ECvmhqV2UDFBgvIHJW/tHEcznKJYibVf5G+ohXm0/fKKIkWKzML7JG+C5nB+JIAyPvMdUPE4rgU+VmmDRCaVR9fx1yre1hVW1Q/JsrTtntipqVWRCLPeqR2k6/rxhxoFhlM7fWTVUNrljZDxfKBR7+0mkJNVdq/i0B1ntvvr+27mYwKTeP6TCql/l7pfVW+nXFaAU7wCQSmDTq/84eIISGgOiPTE4fWlSumlscBlDQfq6sTfms+wDZw4r5BIy2jYXYJQfRFJjAlRquGhicjSecZ/JA6xWwZGhNV3Wp0AsAISsgCwTle5HumpG4/mNf1G8a0ZngEA+cV+oUkB2i/DeKqjpf/HktKPhRw24VTYT2O5JtmfZ8CM6lbx5iNapLEgxhbhG/40rMxUanMaSduT9dLRN77/JWfEX6gI8h05ReuZGXzTTI0RTPKXczwTW3MORmcmeS73IODAkgm8cEGiSn00YJGrC+VlwTOywqx8nOBzxNRvEZ220/NA1SjehuKgFho7LHR6rWPiwpn22k0NbBtiKQIiJMfkoBqGAdhyiLydAIj1s5ZiC5NjCUfCuNlkjYovhX//EidU6bPxWj8ZTKWUFrkgbsfez8Kl4SUd6ckATJ6VVcQyzNpEYfCgC2P3/EnTObcd7/zI01hDn1L5h09EoZt8KO9qmujVWaB8CoTT0pSsteRwzA/NbQni2FWO2EzlydNYMcQfVBN57kqop9vBWNU08tYUG6nkzL6EMVZqTck5Y9Ur/5mhwMUfiJUN5SZDC6DUnW+KvrfiGMehURNtL6sUxXIysnjR8aUM+BCZ0M1XM7Fjxi7XWnPRD4/xLM
  template:
    metadata:
      creationTimestamp: null
      name: harbor-pull
      namespace: agile
    type: kubernetes.io/dockerconfigjson
