---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-push
  namespace: arc-runners
spec:
  encryptedData:
    .dockerconfigjson: AgBRjap2nxLNHHPv2GvQ0oxEv/JHGh2ksq3RR1MpDTVe0wL1W2ToLgJ9URGwwvvOTosf6yb2nN+1LQd9WHoJSkK9Mu+hIHPjRulsMopCP54iEnHa7AjkXYFapqo4t9TjcmDUCAgSJsV9ikNdyaSbhxPal1D8ELMtleVIsEQoRO+rNT73WJIfKZz2Nu5h0QN76Wa+gu7lvheNtbFrrwieHnFOpbnAUtfWvPxmdVoDds/IB2hyub16nTt5duHFTQoWE5wWigTS2QXkkJilvyb7f9+Wre4RbK4lbecJSNvFCkG8KT3ohiU4l/dd4kZ5t/MPdzoTXYUrk5tq1jq09p5bTVK0/XKONRdbzbsKrX88Dm3bRPokDZ0whhQoJSgscuAnJVzdJsSMzO6pba8OlTphuYCjYXv9bHvcF64Hu9QMtXiVrcKs0HYjtsx09JwKjIXZ8K6VFH5mDbm6cknYu9gWqxYcPtfmjWeKYTGaIz+zkLK3izfGPMmRBoCJar+brv/dgN5FHTgSI0VxKJCPkfP7DFEaPJpEQlp+tjH/GyqNI9AaWWW9Y1KCA/FrHJX9CsZnEsAHO+zSbKQ3P/Mpb4iLSg7+bnbXVF7tE8Ahwx1z1K1M6k+lZR9Qf87Uhd/AESXWnDf3DzixV22Gk+96qXzIJb+3Wm9WmemRDHnkow9T8ylrPL+eT1YOq0KdpOCxZ1A1PO37klVq5lKixgCs26GkoEpZITXm5Z13AFDYLxVwyiqtmbpv+SkejfuDypmUiu9PZCIScZqHvsWn4zlR1yJ9c/uDFPqJiaoNxCD9qKbQDbIBY/GY/66N3oZSRdzsY8m83yr7t7F/P3ltGPBJZRtPOSAUpwEpiyOwZbIcZTYAuV39eWUQMfzEe1Xg/8uYf7csodHWI+YD3sgkFqX65pmVqL0m9N2tXtkHNg0MF9y8/Ur1G6mB2WEPvjzlQ++UgxR2/nfKyA3cdNFsa4e/1hV/kHano1s6MBV7pL99T9pTOWcBqko4sIAmF563
  template:
    metadata:
      name: harbor-push
      namespace: arc-runners
    type: kubernetes.io/dockerconfigjson
