---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-push
  namespace: arc-runners
spec:
  encryptedData:
    .dockerconfigjson: AgApw32u5/aBjADH+rjCDo03DfcNfbpdb8jfv9AY0X/uI5CSytTjJuA7yFiBnzfLkA2LMtiOmhilIXRXpLCv3mKrpugXRl2eG26I17I1KQdJT7J7f6bjF9BrmcEMIzQIbxfNa0Sx0TGeVbPXKe28eWjr9BreY0xUn33i43dV2PwMj4LnVL+4paHKUPKiBmvPgNmeEZ+qzdaZzBAIi3issFRlzwK1xvxXHLJZesOGZnjGAdEaNNpkUlaX60eBUSCkuvXKbmzpOTRSrTGF9uVrMurL1pnHQdsRnPjoGvzCbkDSmldkVEVPQ0dl6PxNgjQGD6d+zd2MNIwkcfcc+TMxPTMxGBuJGvsQGzfNwlke8+C7DAN2Y0hbFUtS2SMpRhQNzjYWgrnskQ0F7umvX1mi0EBII8FrKVEWsX1xmmS5hU/pO2xyYPxQV5OWZbfSFzMKTxJqa7+B74tIFbak6pr1hGN7SIL7p2C2Os1tIBVkfPXJvbQplaSHLGYPFSKfp2hl8mUYnYFOfLThN6cUWyKj5dSfhmYrG5s9umw6KoNgwdZMeBiRBTqDNehfPA7/XsTll4cPqJQqFpwBzDTPlGCyZXdPLRFhcp00GWMbUNbK+91mPWng6FMyskTswC1Y9nYjE/pB5UcLb4f4FpX4LrqBjRKBc7KpioNGoYw5TqJluWug37T8VWVvu+s0GApDfMI2b0V67j8asOUAuSD2AnI7HHPYCMEP575IqAiMdg71AJmTJC/EusW35ro7Z0S/A3teJsWFoXuD/uEVjNudjhj3WBqli/5EGs0WOf/BCLymBMWTSdlwooe4MZkPWIDtq9kqFqhXVZ/jG/WgwSC8bYNpPOgKFRpiqyIYqsPloMkOZxyYv2dBpoy/04JavJBNnGi8qYBMW/KubPxji4AAcrnkVDyfpwCFs4CBNOMcWhw+icVj4UXADNNfDvAOUTkl2q+P35tnoqYmqFhZzq+UeggR76pS7YAXcP9y1ePdowZMG0o8GnamiX2itJ1N/Zcc
  template:
    metadata:
      name: harbor-push
      namespace: arc-runners
    type: kubernetes.io/dockerconfigjson
