---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-push
  namespace: arc-runners
spec:
  encryptedData:
    .dockerconfigjson: AgA1/rAZ35ioY2pej6rZ9QugNUyh6MgASx0ayhOPoBTrqgR5NLhiRs/hhFeSkIxicXa3aKgvtHd5H4jnOd6t2hnRUX2ylJntTUx+DyRSnK8MGdXFm3XLVY6w1wDN0hFJTcTvJ/rTiPlYnHPoXem0xo3VYYO7W2PPLwImUkQHxdGCcOcHlUtAJC6sCsjVL9SzI0vFBfK3cb44DZkJU+BF5cuSXzeyjgytihvULpkdLFPLL+uSJgZVegWOgrcdTl7GvNcGG5rlfTfFTgBzqIj5iaPOK2ND0v2S+O9/2w0yfHFEI5HVBFKRdS4ouH7WfhuElYutd+77Ff6liRm2GEVygw+sMUUK8K1eFrPsbuMz6oZe4hKSDSq7Pi7Nk+YUAaAOkxHlTM/ecZ32jjMdw249pxaO4cQjbtQSyjgXZv5Blw22MBXXyNA1NTCebOCN7r//vtdWzBTD5rQZGEb+KYiexWUoD1M/AcxkhFJohAgCYRDTrPI23Qdpg7lxo+EZD1DC7Uk3PbL+QdQyFYBPcKZYwKHDtPIOQVFIdbRuooUDgUIwrPPkQ/H24Jinnf+T+VS1hzhW+3XscJtbdXhK3Ok67P2TZmGTZTQ6B32jh1VtZiHP0peZPis4NihAKSmVjAA1+C2ISuYkcTs+C1bGnEkkc53hWe75cZcC5FpoRLhOuYaow8ccmMCGQBRdtRKDPXy4FAGzabV/QP/slyNpNOJrqYkJtBDsDXz9u7tw1ryRiE4dfYEhBCchtBBqvHoerC4V/YV2zcjLKLoDSo/GnSyly8mmnGSgln1JjwROka8aIVcu1GAEt2AQmG2xbOln2fHXbJIsSCQuzKIKXCqdVxZsUR6u6t6HmF7UXw5q+ysyIOYFVJISrcseRujRr4q+AoTEPw8SBvgtDS3jpbMDgaM/fLBaXPsNVc+FkD7IMQ3VCsUYd/cSGU8wS6XiE9nuU6Xvpsq5ABNpexKIhbwkoEK/Dl/nGP9QOhARpxkt9AbU9KbUKrpOwwWQpFOkBJJ2
  template:
    metadata:
      name: harbor-push
      namespace: arc-runners
    type: kubernetes.io/dockerconfigjson
