---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vault-provider-creds
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgCbJGklXNZYiaksWS67Csev4CTtMATp3Gc46HoWyTCfGO/CbFZniugnghHHCg2Pzyek7mXDjGCg4mdiPsYG8vP2QUmrrU3iYnI5n4VcK5Ih9KuIf/7vUGBRLf46i5NIdoQI6NNvSkKNHGRDCZvEnO2uY1qKXoiPkQeTktlaZp+B5Ba/2SBlj4GggYZBTkTeWQoMkp1QNqC45V/JHDazQHWn6RifUGaGYTjb9HEJLUzApsZxoW43xWqn8WWQx1+ZvQsnAjyFmKKiIwi1b1Ma1RV4yaQ6Yqnh1Sw1LZIKzJScJJWSZQopQdu0zkHQ45wx4H4ptF0AphOl79qVSiho5mmHZBYRPtz6vDCNR4O7zkSctXJYvvdbRi2gGqmkYKoWsXge90khe+ssxau/9aQQR6unNTI5HFbJnCrFFqpxYKWEr5CpLbolkBji6R2+gBhOWZf1/LtQ9/F2aFPj6q/ojC56K46suFMD5svzbPJdFQ9P27RimbvIVsT2iCrArV68kHb4l2qmNh5KYjcIr3yRRAqm6Y6F9XMwA/Ph8vrKy4UttzcOC6VxcLxyJO+8OTGl5Kx9Ullj4r4rxeghAtSol55b8cTMyHo1ppUBFY1j14fpIxCekoiKNNvpP8IhoMZa+izf5/ki/wf+e9Duyk6ysBYXqqYCkepm3cHzKvsnRkVR8w8/Ywa8hJxWs7H6TAe6AoDrS2Es+T6K5aD0cGn4nnoNDaNkqOT5GBkoqjBzOXn6yNMmaxjXSkmX8dQfgNt8IYsQrjKnuBHM5MpYBXNZq2U9b/64YA5AC5Y9DhkUXUeNXumdM7f73609n2yEh/QuPllD7583w20FX8/6gfD/IVuLQ9XtA95MUa0tuCg+WVAhc9cj82PrCSovGWlw2i8lTzhznKU+rFAq91wtorf7+2fAcRKlS+o=
  template:
    metadata:
      name: vault-provider-creds
      namespace: crossplane-system
